"""insert default categories

Revision ID: 010b6b7d091f
Revises: 626c8d77fe34
Create Date: 2026-01-03 11:20:28.869677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010b6b7d091f'
down_revision: Union[str, Sequence[str], None] = '626c8d77fe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


products_categories_table = sa.table(
    'products_categories',
    sa.column('name', sa.String),
    sa.column('description', sa.String),
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.bulk_insert(
        products_categories_table,
        [
            {
                'name': 'Cereais',
                'description': 'Categoria de produtos que inclui arroz, feijão, milho, aveia, trigo e outros grãos essenciais para a alimentação diária.',
            },
            {
                'name': 'Bebidas',
                'description': 'Categoria de produtos que abrange refrigerantes, sucos, águas, bebidas alcoólicas e outras opções para hidratação e consumo.',
            },
            {
                'name': 'Limpeza',
                'description': 'Categoria de produtos destinada à higienização e manutenção do ambiente, incluindo detergentes, desinfetantes, sabões e outros itens de limpeza.',
            },
            {
                'name': 'Hortifruti',
                'description': 'Categoria de produtos que inclui frutas, verduras, legumes e outros itens frescos provenientes de hortas e pomares.',
            },
            {
                'name': 'Padaria',
                'description': 'Categoria de produtos que engloba pães, bolos, tortas, biscoitos e outras delícias assadas, típicas de uma padaria.',
            },
            {
                'name': 'Congelados',
                'description': 'Categoria de produtos que abrange alimentos congelados, como refeições prontas, vegetais, carnes e sobremesas, destinados à conservação por longos períodos.',
            },
            {
                'name': 'Açougues',
                'description': 'Categoria de produtos que inclui carnes frescas, como bovina, suína, aves e outros cortes, disponíveis em açougues e seções de carnes.',
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text('DELETE FROM products_categories')
    )
    # ### end Alembic commands ###
