"""seed users add admin

Revision ID: 626c8d77fe34
Revises: b66aedbf9498
Create Date: 2026-01-01 23:02:09.854084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pwdlib import PasswordHash

# revision identifiers, used by Alembic.
revision: str = '626c8d77fe34'
down_revision: Union[str, Sequence[str], None] = 'b66aedbf9498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_table = sa.table(
    'users',
    sa.column('username', sa.String),
    sa.column('email', sa.String),
    sa.column('full_name', sa.String),
    sa.column('hashed_password', sa.String),
    sa.column('is_active', sa.Boolean),
    sa.column('role', sa.String),
)

password_hasher = PasswordHash.recommended()

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        user_table,
        [
            {
                'username': 'admin',
                'email': 'admin@admin.com',
                'full_name': 'super admin',
                'hashed_password': password_hasher.hash('12345678'),
                'is_active': True,
                'role': 'admin',
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute(
        sa.text('DELETE FROM users WHERE email = "admin@admin.com"')
    )

    # ### end Alembic commands ###
