"""add product model

Revision ID: b66aedbf9498
Revises: b64fb30a8741
Create Date: 2026-01-01 22:59:41.617536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66aedbf9498'
down_revision: Union[str, Sequence[str], None] = 'b64fb30a8741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_categories_description'), 'products_categories', ['description'], unique=False)
    op.create_index(op.f('ix_products_categories_id'), 'products_categories', ['id'], unique=False)
    op.create_index(op.f('ix_products_categories_name'), 'products_categories', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bar_code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['products_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_bar_code'), 'products', ['bar_code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_bar_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_products_categories_name'), table_name='products_categories')
    op.drop_index(op.f('ix_products_categories_id'), table_name='products_categories')
    op.drop_index(op.f('ix_products_categories_description'), table_name='products_categories')
    op.drop_table('products_categories')
    # ### end Alembic commands ###
